library(knitr)
library(ggplot2)
library(grid)
library(gridExtra)
library(RColorBrewer)
library(colorspace)
library(colorRamps)
library(dendextend)
library(gplots)
library(hexbin)
library(MASS)
library(dichromat)
library(reshape2)
library(lattice)
library(tidyverse)
library(datasets)
library(forecast)
library(ggfortify)
library(OpenStreetMap)
library(rgdal)
library(ggvis)
library(DiagrammeR)
library(dygraphs)
library(leaflet)
library(graph)
library(Rgraphviz)
library(plotly)
library(heatmaply)
library(maps)
library(igraph)
library(miniCRAN)
library(wordcloud)
library(tm)
library(SnowballC)
library(corpcor)
library(rgl)
library(scatterplot3d)
library(VennDiagram)
library(ggbio)
library(biovizBase)
library(GenomicRanges)
library(EnsDb.Hsapiens.v75)
library(survminer)
library(survival)





